### ISSUE TITLE
Re: Want to subscribe —-may have accidentally paid 2x

### ISSUE THREAD

**Issue by kelliv** [Writer-Sonic/Ai-Writer-#2]
Hiya
I used PayPal and did not know my bank put a security hold on my first attempt at a transaction for the $200 package for one year.

**Comment by kelliv** [comment]
Can you confirm that you have at least one payment for the new subscription? If the second payment also goes through can you please refund it? Please confirm either scenario. Thank you and happy holidays

**Comment by aryan1107** [comment]
Hi sorry to hear that for app payment is managed by Apple.  If you are using the app please go to subscription into your IOS subscription settings it will show you everything from there you can manage and even ask for refund.

Hope this helps.
