### ISSUE TITLE
Upgrade to 100.000 words per month not working?

### ISSUE THREAD

**Issue by AIsteve2023** [Writer-Sonic/Ai-Writer-#5]
Hi i've tried to upgrade multiple times but it doesnt seem to worK when i upgrade?

**Comment by aryan1107** [comment]
Hi can you update to latest version of the app and then send me screenshot
of word count.

Also when you update to latest version it will provide you your unique id
can you please send that picture also.

Best,
Aryan

**Comment by aryan1107** [comment]
Can you confirm if the issue is resolved?
